#!/usr/bin/env bash
set -euo pipefail

# =========[ MODUŁ 02: WORKSPACE ←→ COMFYUI ]=========

WORKDIR="${WORKDIR:-/workspace}"

# Znane możliwe lokalizacje ComfyUI
CANDIDATES=(
  "${WORKDIR}/ComfyUI"
  "/workspace/ComfyUI"
  "/opt/ComfyUI"
)
COMFY_DIR=""
for c in "${CANDIDATES[@]}"; do
  if [ -d "$c" ]; then COMFY_DIR="$c"; break; fi
done
[ -z "$COMFY_DIR" ] && COMFY_DIR="${WORKDIR}/ComfyUI" && mkdir -p "${COMFY_DIR}"

echo "[workspace] COMFY_DIR = ${COMFY_DIR}"

# 1) Podstawowe katalogi robocze (trwałe)
mkdir -p "${WORKDIR}/input" "${WORKDIR}/output" "${WORKDIR}/workflows" "${WORKDIR}/logs" "${WORKDIR}/models"

# 2) Skopiuj strukturę katalogów z ComfyUI/models → /workspace/models (bez plików)
if [ -d "${COMFY_DIR}/models" ]; then
  echo "[workspace] kopiuję strukturę katalogów models → workspace"
  if command -v rsync >/dev/null 2>&1; then
    rsync -a -f "+ */" -f "- *" "${COMFY_DIR}/models/" "${WORKDIR}/models/" || true
  else
    while IFS= read -r -d '' d; do
      rel="${d#"${COMFY_DIR}/models/"}"
      mkdir -p "${WORKDIR}/models/${rel}"
    done < <(find "${COMFY_DIR}/models" -type d -print0 2>/dev/null || true)
  fi

  # 3) Przenieś istniejące pliki do workspace
  while IFS= read -r -d '' f; do
    rel="${f#"${COMFY_DIR}/models/"}"
    dest="${WORKDIR}/models/${rel}"
    mkdir -p "$(dirname "$dest")"
    if [ -e "$dest" ]; then
      echo "[workspace] pomijam (istnieje): ${dest}"
    else
      echo "[workspace] przenoszę: ${rel}"
      mv "$f" "$dest" || true
    fi
  done < <(find "${COMFY_DIR}/models" -type f -print0 2>/dev/null || true)

  # 4) Podmień katalogi w ComfyUI/models na symlinki → /workspace/models
  while IFS= read -r -d '' d; do
    rel="${d#"${COMFY_DIR}/models/"}"
    [ -z "$rel" ] && continue
    mkdir -p "${WORKDIR}/models/${rel}"
    ln -sfn "${WORKDIR}/models/${rel}" "${COMFY_DIR}/models/${rel}"
  done < <(find "${COMFY_DIR}/models" -maxdepth 1 -mindepth 1 -type d -print0 2>/dev/null || true)
else
  mkdir -p "${COMFY_DIR}/models"
  ln -sfn "${WORKDIR}/models" "${COMFY_DIR}/models"
fi

# 5) Zalinkuj input/output dla wygody
ln -sfn "${WORKDIR}/input"  "${COMFY_DIR}/input"
ln -sfn "${WORKDIR}/output" "${COMFY_DIR}/output"

# 6) Wygeneruj extra_model_paths.yaml
YAML="${COMFY_DIR}/extra_model_paths.yaml"
cat > "$YAML" <<'EOF'
# Auto-generated by Module 02
comfyui:
  base_path: /workspace/
  is_default: true
  checkpoints: models/checkpoints/
  clip: models/clip/
  clip_vision: models/clip_vision/
  diffusion_models: |
    models/diffusion_models
    models/unet
  vae: models/vae/
  loras: models/loras/
  text_encoders: models/text_encoders/
  controlnet: models/controlnet/
  upscale_models: models/upscale_models/
  embeddings: models/embeddings/
EOF

echo "[workspace] zapisano ${YAML}"
echo "[workspace] gotowe."
# =========[ /MODUŁ 02 ]=========
